### ISSUE TITLE
Sayma v2 Design Review 

### ISSUE THREAD

**Issue by jbqubit** [m-labs/sinara#604] opened 2018-12-14 22:52 UTC
@marmeladapk and @jbqubit put together a spreadsheet that details the design review process for Sayma v2. It includes the HT1 and HT2 review stages. It calls out detailed topics to review, a detailed checklist, assignments and deadlines. Named reviewers will be provided with write access using their google credentials. Please read instructions. Note that the layout design questions are still being refined. Here's a read-only link. 

https://docs.google.com/spreadsheets/d/1DefjWAyn5593QPaktRCj8P-1UrTjZG76obw2nbPDgOk/edit?usp=sharing

If an assignment is problematic or you'd like to see another review topic please discuss in this Issue. 

@sbourdeauducq @jordens @dhslichter @hartytp @gkasprow @tprzywoz

**Comment by jordens** [comment] 2018-12-14 22:55
I get access denied.

**Comment by dnadlinger** [comment] 2018-12-14 22:55
(That link seems to require credentials as well.)

**Comment by marmeladapk** [comment] 2018-12-14 22:58
Link updated. @jordens @klickverbot 

Works in private browser session.

**Comment by jordens** [comment] 2018-12-15 12:02
It's going to be inefficient and error-prone to split tasks like the "all unused inputs terminated" and "diode polarity" checking among 4-6 different groups and people. If you want to split the review, I'd e.g. rather have someone do schematic reviews at the fundamental level (diodes and inputs) and someone else with expertise in different conceptual areas cover bus logic, transcievers lanes and clocking networks.
The person checking some sheet/area (like FPGA decoupling) on Metlino should be whoever did or does it on Sayma.

**Comment by marmeladapk** [comment] 2018-12-17 13:15
@jordens The idea was, that each person has only too look at and check as few pages of schematics and data sheets as possible. If someone is checking if issues are properly fixed he can also look at N/C pins, inputs etc.

**Comment by jbqubit** [comment] 2018-12-17 17:16
@jordens The document that @marmeladapk and I put together is structured to make sure to ensure that the review is comprehensive across the Sayma v1 to v2 diffs.  Indeed there are many ways to scale this fish. Given the time available I'd like you and @sbourdeauducq to divvy up the design review tasks assigned to M-Labs. If you prefer to conduct a lateral review of a particular aspect (eg diodes and inputs) across all schematics please call that shot in this Issue and annotate the corresponding rows in the spreadsheet indicating that you've got that aspect covered. Everyone will appreciate your contributions to the review.

**Comment by jordens** [comment] 2018-12-17 17:52
Let's have M-Labs focus on the areas and aspects that we are most qualified to review to the best use of the available funding.

**Comment by jbqubit** [comment] 2018-12-18 17:07
@jordens I appreciate your comment but it doesn't help move the design review forward. Working from the current state of the HT1.5 and HT2 spreadsheet, do you agree that the roles assigned to M-Labs are within the qualifications of M-Labs to review?

**Comment by jbqubit** [comment] 2018-12-18 20:19
@sbourdeauducq Raised a question in [Issue](https://github.com/sinara-hw/sinara/issues/566#issuecomment-448326177). He is recalling the following outcome of a discussion with Xilinx tech support related to Sayma v2 (April 2018).

> Conclusion of Xilinx service request (10440122).  Vccint + Vccint_IO rail should be 0.95 V. Xilinx use of HyperLynx modeling tool. Found that at 9.8A there is a max voltage drop of 105.8mV. Which is too much sag. 

Does the Creotech secondary design review include repeat of signal integrity and power analysis simulations? Do we want this?

**Comment by jbqubit** [comment] 2018-12-18 20:41
https://github.com/sinara-hw/Sayma_AMC/issues/6#issuecomment-448186699

@jordens @sbourdeauducq Funds are on hand now at M-Labs that can be used to start the design review. I've asked several times for a quote to provide additional funding. We all really value your participation in this process. Please don't imply that lack of funding is an obstacle to your participation in the design review.

**Comment by hartytp** [comment] 2018-12-18 20:46
@jbqubit I think the comment about funding there replied to funding for servo gateware/software development, not to general funding for Sayma v2.0 design reviews. AFAICT there is no plan to fund servo development, so that comment is valid.

**Comment by jbqubit** [comment] 2018-12-18 20:56
> AFAICT there is no plan to fund servo development, so that comment is valid.

Indeed, there is presently no formal support in place for Sayma v2 servo development. As I understand https://github.com/sinara-hw/Sayma_AMC/issues/6 is to equip the hardware with sufficient IO to support a possible future servo. Apologies if I misunderstood the scope of @jordens comment.

**Comment by hartytp** [comment] 2018-12-18 20:59
> As I understand sinara-hw/Sayma_AMC#6 is to equip the hardware with sufficient IO to support a possible future servo. 

That's correct. However, without first discussing detailed requirements and then designing the servo, it's hard to guarantee that this will actually work as intended. With the funding and time available, we've done the best we can, and checked the obvious things. It will probably work fine.

**Comment by sbourdeauducq** [comment] 2018-12-19 12:54
>  I've asked several times for a quote to provide additional funding.

You kept asking during the course of about a week; sorry, but we need more time, especially with all the things that can go wrong.

**Comment by hartytp** [comment] 2019-03-07 14:30
@gkasprow I'll have some time this evening to review schematics. Do you think they'll be ready by then.

Also, there are a few outstanding Sayma issues in this repo. Can they be closed now?

**Comment by hartytp** [comment] 2019-03-11 21:23
@jbqubit can we close this issue?

**Closed as completed by hartytp** 2019-03-11 21:23 UTC
